#!/bin/bash
jtree(){
   cd bin/
   find ../src/ -type f -name "*.java" > sources.txt
   javac -d ./ @sources.txt
   mv sources.txt .sources.txt 
   echo -e "\n  ::: Project tree :::\n"
   tree
   echo -n "Package: "
   read pkg
   echo -n "Classname: "
   read class
   echo ""
   java -cp $PWD $pkg.$class
   mv .sources.txt sources.txt
   cd ../
}
if ! command -v tree &> /dev/null;then
   yes | sudo pacman -S tree
fi
if [ -d "bin" ]; then
   jtree
else
   mkdir bin
   jtree
fi
