#!/bin/bash
jcomp(){
   cd bin/
   find ../src/ -type f -name "*.java" > sources.txt
   javac -d ./ @sources.txt
   mv sources.txt .sources.txt 
   echo -e "\n  ::: Project tree :::\n"
   tree
   echo -n "Package: "
   read pkg
   echo -n "Classname: "
   read class
   echo ""
   java -cp $PWD $pkg.$class
   mv .sources.txt sources.txt
   cd ../
}
jdoc(){
   cd doc/
   find ../src/ -type f -name "*.java" > sources.txt
   javadoc -d ./ @sources.txt
   cd ../
}
os=$(grep -E '^(PRETTY_NAME|NAME)=' /etc/os-release)
if [[ $os == *'Arch'* ]] || [[ $os == *'Parabola'* ]]; then
   if ! command -v tree &> /dev/null;then
      yes | sudo pacman -S tree
   fi
elif [[ $os == *'Ubuntu'* ]] || [[ $os == *'Debian'* ]]; then
   if ! command -v tree &> /dev/null;then
      sudo apt-get install tree
   fi
elif [[ $os == *'Fedora'* ]]; then
   if ! command -v tree &> /dev/null;then
      sudo dnf install tree
   fi
fi
if [ -d "doc" ]; then
   jdoc
else
   mkdir doc
   jdoc
fi
if [ -d "bin" ]; then
   jcomp
else
   mkdir bin
   jcomp
fi
